# KAROTENOIDIDE ERALDAMINE, IDENTIFITSEERIMINE ja SISALDUSE MÄÄRAMINE värskes köögiviljas

## Kuupäev

2023-03-01

## Töö eesmärgid

1. Taimse materjali karoteinoidide ja klorofülli neeldumisspekter määratud.

2. Uuritava proovi karotenoidne koostis iseloomustatud.

3. β-karoteeni sisaldus uuritavas proovis määratud.

4. Klorofülli olemasolu kindlaks tehtud.

## Kasutatud töövahendid

1. Nuga,

2. riiv,

3. uhmer,

4. liiv,

5. paberfilter,

6. klaaslehter,

7. mõõtesilinder,

8. spaatel,

9. kvartsküvetid,

10. pipett,

11. klaaspulk.

## Reagentide kogused

1. \qty{0,91}{\g} kollast porgandit,

2. \qty{4,9}{\g} veevaba \ce{Na_2SO_4},

## Töö käik

Selle töö teostasin Ants-Andre Länsiga:

1. Kaalusime taimse materjali.

2. Peenestasin proovi noaga.

3. Hakitud proovi asetasime uhmrisse koos väikese koguse pestud liivaga.

4. Uhmerdasime kuni ühtlase massi saamiseni.

5. Lisasime uhmrisse naatriumsulfaadi.

6. Jätkasime massi hõõrumist.

7. Peenestatud massile lisasime \qty{5}{\ml} heksaani.

8.  Segasime hoolikalt spaatliga.

    ```{r label = "hexane"}
    quantity_of_hexane = 8 + 2.5 + 2.5 + 3

    ```

9. Lisasime \qty{`r as.character(quantity_of_hexane)`}{\ml} heksaani.

10. Filtrisime mõõtesilindrisse.

11. Lisasime \qty{6}{\ml} heksaani.

12. Filtrisime mõõtesilindrisse.

13. Mõõtsime mõõtesilindriga saadud ekstrakti üldmahuks \qty{18}{\ml}.

## Arutelu
